In [9]:
import sklearn as sk
import pandas as pd 
import numpy as np 
import warnings
import seaborn as sns
# warnings.filterwarnings{'ignore'}

In [3]:
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

print("All set 💯")

All set 💯

In [4]:
df = pd.read_csv("insurance.csv")
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

EDA

In [5]:
df.shape

(1338, 7)

In [6]:
df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [7]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [8]:
df.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [10]:
numeric_columns = ['age', 'bmi', 'children', 'charges']
for col in numeric_columns:
    plt.figure(figSize=(6, 4))
    sns.histplot(df[col], kde = True, bins = 20)

AttributeError: Figure.set() got an unexpected keyword argument 'figSize'

In [13]:
# label encoding for sex 
df["sex"] = df["sex"].map({'male': 0, 'female': 1})
df.head()

   age  sex     bmi  children smoker     region      charges
0   19  NaN  27.900         0    yes  southwest  16884.92400
1   18  NaN  33.770         1     no  southeast   1725.55230
2   28  NaN  33.000         3     no  southeast   4449.46200
3   33  NaN  22.705         0     no  northwest  21984.47061
4   32  NaN  28.880         0     no  northwest   3866.85520

In [14]:
df.dtypes

age           int64
sex         float64
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

In [15]:
df

      age  sex     bmi  children smoker     region      charges
0      19  NaN  27.900         0    yes  southwest  16884.92400
1      18  NaN  33.770         1     no  southeast   1725.55230
2      28  NaN  33.000         3     no  southeast   4449.46200
3      33  NaN  22.705         0     no  northwest  21984.47061
4      32  NaN  28.880         0     no  northwest   3866.85520
...   ...  ...     ...       ...    ...        ...          ...
1333   50  NaN  30.970         3     no  northwest  10600.54830
1334   18  NaN  31.920         0     no  northeast   2205.98080
1335   18  NaN  36.850         0     no  southeast   1629.83350
1336   21  NaN  25.800         0     no  southwest   2007.94500
1337   61  NaN  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [16]:
 df["sex"].value_counts()

Series([], Name: count, dtype: int64)

In [17]:
df['smoker'].value_counts()

smoker
no     1064
yes     274
Name: count, dtype: int64

In [18]:
df['sex'].value_counts()

Series([], Name: count, dtype: int64)

In [19]:
df['smoker'] = df['smoker'].map({'no' : 0,'yes' : 1})

In [20]:
df

      age  sex     bmi  children  smoker     region      charges
0      19  NaN  27.900         0       1  southwest  16884.92400
1      18  NaN  33.770         1       0  southeast   1725.55230
2      28  NaN  33.000         3       0  southeast   4449.46200
3      33  NaN  22.705         0       0  northwest  21984.47061
4      32  NaN  28.880         0       0  northwest   3866.85520
...   ...  ...     ...       ...     ...        ...          ...
1333   50  NaN  30.970         3       0  northwest  10600.54830
1334   18  NaN  31.920         0       0  northeast   2205.98080
1335   18  NaN  36.850         0       0  southeast   1629.83350
1336   21  NaN  25.800         0       0  southwest   2007.94500
1337   61  NaN  29.070         0       1  northwest  29141.36030

[1338 rows x 7 columns]

In [21]:
df['region'].value_counts()

region
southeast    364
southwest    325
northwest    325
northeast    324
Name: count, dtype: int64

In [22]:
df = pd.get_dummies(df, columns = ['region'], drop_first=True)

In [23]:
df

,age,sex,bmi,children,smoker,charges,region_northwest,region_southeast,region_southwest
0,19,NaN,27.900,0,1,16884.92400,False,False,True
1,18,NaN,33.770,1,0,1725.55230,False,True,False
2,28,NaN,33.000,3,0,4449.46200,False,True,False
3,33,NaN,22.705,0,0,21984.47061,True,False,False
4,32,NaN,28.880,0,0,3866.85520,True,False,False
...,...,...,...,...,...,...,...,...,...
1333,50,NaN,30.970,3,0,10600.54830,True,False,False
1334,18,NaN,31.920,0,0,2205.98080,False,False,False
1335,18,NaN,36.850,0,0,1629.83350,False,True,False
1336,21,NaN,25.800,0,0,2007.94500,False,False,True
1337,61,NaN,29.070,0,1,29141.36030,True,False,False